# Default configuration for RL Meal Planning System

algorithm: "PPO"

environment:
  max_steps: 50
  max_meals_per_day: 5
  min_calories: 1200.0
  max_calories: 3000.0
  target_protein_ratio: 0.25
  target_carbs_ratio: 0.45
  target_fats_ratio: 0.30
  variety_penalty: 0.1
  satisfaction_weight: 0.3
  nutrition_weight: 0.5
  variety_weight: 0.2

agent:
  learning_rate: 3e-4
  batch_size: 64
  buffer_size: 10000
  gamma: 0.99
  tau: 0.005
  target_update_freq: 1000
  policy_freq: 2
  noise_clip: 0.5
  policy_noise: 0.2
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

database:
  usda_api_key: null
  openfoodfacts_url: "https://world.openfoodfacts.org/cgi/search.pl"
  cache_dir: "data/cache"
  update_frequency: 7
  max_foods_per_category: 1000

feedback:
  feedback_window: 30
  min_feedback_threshold: 5
  feedback_decay_rate: 0.95
  satisfaction_threshold: 0.7

training_episodes: 1000
evaluation_episodes: 100
save_frequency: 100

log_level: "INFO"
log_file: "logs/meal_planning.log"

model_dir: "models"
checkpoint_dir: "checkpoints" 